### ISSUE TITLE
Minor spelling in studyLevel1.m

### ISSUE THREAD

**Issue by VisLab** [BigEEGConsortium/ESS#4]
Line 2: manipulation
Line 5: new and =
Line 24: missing of
Line 63 missing about
Line 71: notice
Line 89: Information
Line 107 "an instance"
Line 108: exist
Line 120 recommended
Line 125: unprompted
Line 145: if  the folder 'container is provided instead of filename
Line 175: recording
Line 185: and
Line 230: places
Line 247: mistakenly remove "have" 
Line 248: Nodes
Line 418: parameter
Lines 590 and 591: sampling rates
Line 1066:  <project>
Line 1622: length
Line 1671:   characters
Line 1906: feet
Line 2001: instance
Line 2028: Recording parameter set

Line 132: recommended
Line 135:  question marks instead of quoted quotes

**Comment by bigdelys** [comment]
Solved in the new commit.
