### ISSUE TITLE
Crashes when eventInstanceFile is empty

### ISSUE THREAD

**Issue by VisLab** [BigEEGConsortium/ESS#5]
When obj.sessionTaskInfo(i).dataRecording(j).eventInstanceFile is [] (default) rather than '', crashes on line 2610: 

fileNameFromObjisEmpty = isempty(strtrim(fileNameFromObj));

suggest changing:
 fileNameFromObjisEmpty = isempty(fileNameFromObj) || ...
                            isempty(strtrim(fileNameFromObj));

Also crashes on line 2634.  Same issue.

**Comment by bigdelys** [comment]
Fixed, thank you.
